# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20160609_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
